/* Generated by Yosys 0.65 (git sha1 b85cad634, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* src = "alu.v:1.1-8.10" *)
module alu(result, a, b, sel);
  (* src = "alu.v:2.15-2.21" *)
  output [2:0] result;
  wire [2:0] result;
  (* src = "alu.v:3.15-3.16" *)
  input [1:0] a;
  wire [1:0] a;
  (* src = "alu.v:4.15-4.16" *)
  input [1:0] b;
  wire [1:0] b;
  (* src = "alu.v:5.15-5.18" *)
  input sel;
  wire sel;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  sky130_fd_sc_hd__clkinv_1 _08_ (
    .A(b[1]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__clkinv_1 _09_ (
    .A(b[0]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xnor2_1 _10_ (
    .A(b[1]),
    .B(a[1]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nand2_1 _11_ (
    .A(a[0]),
    .B(b[0]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__xor2_1 _12_ (
    .A(a[0]),
    .B(b[0]),
    .X(result[0])
  );
  sky130_fd_sc_hd__nand3b_1 _13_ (
    .A_N(a[0]),
    .B(b[0]),
    .C(sel),
    .Y(_03_)
  );
  sky130_fd_sc_hd__o21ai_0 _14_ (
    .A1(sel),
    .A2(_02_),
    .B1(_03_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _15_ (
    .A(_01_),
    .B(_04_),
    .Y(result[1])
  );
  sky130_fd_sc_hd__o221a_1 _16_ (
    .A1(_07_),
    .A2(a[1]),
    .B1(a[0]),
    .B2(_00_),
    .C1(sel),
    .X(_05_)
  );
  sky130_fd_sc_hd__mux2i_1 _17_ (
    .A0(sel),
    .A1(b[1]),
    .S(a[1]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__o32ai_1 _18_ (
    .A1(sel),
    .A2(_01_),
    .A3(_02_),
    .B1(_05_),
    .B2(_06_),
    .Y(result[2])
  );
endmodule

(* src = "counter.v:1.1-13.10" *)
module counter(count, clk, rst);
  (* src = "counter.v:2.19-2.24" *)
  output [3:0] count;
  wire [3:0] count;
  (* src = "counter.v:3.19-3.22" *)
  input clk;
  wire clk;
  (* src = "counter.v:4.19-4.22" *)
  input rst;
  wire rst;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  sky130_fd_sc_hd__and3_1 _08_ (
    .A(count[1]),
    .B(count[0]),
    .C(count[2]),
    .X(_04_)
  );
  sky130_fd_sc_hd__a21oi_1 _09_ (
    .A1(count[1]),
    .A2(count[0]),
    .B1(count[2]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nor3_1 _10_ (
    .A(rst),
    .B(_04_),
    .C(_05_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__a21oi_1 _11_ (
    .A1(count[1]),
    .A2(count[0]),
    .B1(rst),
    .Y(_06_)
  );
  sky130_fd_sc_hd__o21a_1 _12_ (
    .A1(count[1]),
    .A2(count[0]),
    .B1(_06_),
    .X(_01_)
  );
  sky130_fd_sc_hd__nor2_1 _13_ (
    .A(count[0]),
    .B(rst),
    .Y(_02_)
  );
  sky130_fd_sc_hd__a41oi_1 _14_ (
    .A1(count[1]),
    .A2(count[0]),
    .A3(count[3]),
    .A4(count[2]),
    .B1(rst),
    .Y(_07_)
  );
  sky130_fd_sc_hd__o21a_1 _15_ (
    .A1(count[3]),
    .A2(_04_),
    .B1(_07_),
    .X(_03_)
  );
  (* src = "counter.v:7.2-12.5" *)
  sky130_fd_sc_hd__dfxtp_1 _16_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[0])
  );
  (* src = "counter.v:7.2-12.5" *)
  sky130_fd_sc_hd__dfxtp_1 _17_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[1])
  );
  (* src = "counter.v:7.2-12.5" *)
  sky130_fd_sc_hd__dfxtp_1 _18_ (
    .CLK(clk),
    .D(_00_),
    .Q(count[2])
  );
  (* src = "counter.v:7.2-12.5" *)
  sky130_fd_sc_hd__dfxtp_1 _19_ (
    .CLK(clk),
    .D(_03_),
    .Q(count[3])
  );
endmodule

(* top =  1  *)
(* src = "mini_soc.v:1.1-16.10" *)
module mini_soc(soc_out, alu_sel, mux_sel, clk, rst);
  (* src = "mini_soc.v:2.15-2.22" *)
  output [1:0] soc_out;
  wire [1:0] soc_out;
  (* src = "mini_soc.v:3.15-3.22" *)
  input alu_sel;
  wire alu_sel;
  (* src = "mini_soc.v:4.15-4.22" *)
  input mux_sel;
  wire mux_sel;
  (* src = "mini_soc.v:5.15-5.18" *)
  input clk;
  wire clk;
  (* src = "mini_soc.v:6.15-6.18" *)
  input rst;
  wire rst;
  (* src = "mini_soc.v:9.13-9.20" *)
  (* unused_bits = "2" *)
  wire [2:0] alu_out;
  (* src = "mini_soc.v:8.13-8.18" *)
  wire [3:0] count;
  (* module_not_derived = 32'd1 *)
  (* src = "mini_soc.v:13.6-13.77" *)
  alu u_alu (
    .a(count[3:2]),
    .b(count[1:0]),
    .result(alu_out),
    .sel(alu_sel)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "mini_soc.v:11.10-11.57" *)
  counter u_counter (
    .clk(clk),
    .count(count),
    .rst(rst)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "mini_soc.v:15.8-15.80" *)
  mux21 u_mux (
    .in0(count[3:2]),
    .in1(alu_out[1:0]),
    .sel(mux_sel),
    .y(soc_out)
  );
endmodule

(* src = "mux21.v:1.1-8.10" *)
module mux21(y, in0, in1, sel);
  (* src = "mux21.v:2.15-2.16" *)
  output [1:0] y;
  wire [1:0] y;
  (* src = "mux21.v:3.15-3.18" *)
  input [1:0] in0;
  wire [1:0] in0;
  (* src = "mux21.v:4.15-4.18" *)
  input [1:0] in1;
  wire [1:0] in1;
  (* src = "mux21.v:5.14-5.17" *)
  input sel;
  wire sel;
  sky130_fd_sc_hd__mux2_1 _0_ (
    .A0(in0[0]),
    .A1(in1[0]),
    .S(sel),
    .X(y[0])
  );
  sky130_fd_sc_hd__mux2_1 _1_ (
    .A0(in0[1]),
    .A1(in1[1]),
    .S(sel),
    .X(y[1])
  );
endmodule
