/* Generated by Yosys 0.65 (git sha1 b85cad634, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* top =  1  *)
(* src = "and_gate.v:1.1-7.10" *)
module and_gate(y, a, b);
  (* src = "and_gate.v:2.9-2.10" *)
  output y;
  wire y;
  (* src = "and_gate.v:3.9-3.10" *)
  input a;
  wire a;
  (* src = "and_gate.v:4.9-4.10" *)
  input b;
  wire b;
  sky130_fd_sc_hd__and2_0 _0_ (
    .A(a),
    .B(b),
    .X(y)
  );
endmodule
