/* Generated by Yosys 0.65 (git sha1 b85cad634, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* top =  1  *)
(* src = "ha.v:1.1-7.10" *)
module ha(s, c, a, b);
  (* src = "ha.v:2.9-2.10" *)
  output s;
  wire s;
  (* src = "ha.v:2.12-2.13" *)
  output c;
  wire c;
  (* src = "ha.v:3.9-3.10" *)
  input a;
  wire a;
  (* src = "ha.v:3.12-3.13" *)
  input b;
  wire b;
  sky130_fd_sc_hd__and2_0 _0_ (
    .A(a),
    .B(b),
    .X(c)
  );
  sky130_fd_sc_hd__xor2_1 _1_ (
    .A(a),
    .B(b),
    .X(s)
  );
endmodule
