/* Generated by Yosys 0.65 (git sha1 b85cad634, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* top =  1  *)
(* src = "ha.v:1.1-7.10" *)
module ha(s, c, a, b);
  (* src = "ha.v:2.9-2.10" *)
  output s;
  wire s;
  (* src = "ha.v:2.12-2.13" *)
  output c;
  wire c;
  (* src = "ha.v:3.9-3.10" *)
  input a;
  wire a;
  (* src = "ha.v:3.12-3.13" *)
  input b;
  wire b;
  (* src = "ha.v:3.9-3.10" *)
  wire _0_;
  (* src = "ha.v:3.12-3.13" *)
  wire _1_;
  (* src = "ha.v:2.12-2.13" *)
  wire _2_;
  (* src = "ha.v:2.9-2.10" *)
  wire _3_;
  sky130_fd_sc_hd__and2_0 _4_ (
    .A(_0_),
    .B(_1_),
    .X(_2_)
  );
  sky130_fd_sc_hd__xor2_1 _5_ (
    .A(_0_),
    .B(_1_),
    .X(_3_)
  );
  assign _0_ = a;
  assign _1_ = b;
  assign c = _2_;
  assign s = _3_;
endmodule
