/* Generated by Yosys 0.65 (git sha1 b85cad634, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* top =  1  *)
(* src = "fa.v:1.1-7.10" *)
module fa(cout, sum, a, b, cin);
  (* src = "fa.v:2.9-2.13" *)
  output cout;
  wire cout;
  (* src = "fa.v:2.15-2.18" *)
  output sum;
  wire sum;
  (* src = "fa.v:3.9-3.10" *)
  input a;
  wire a;
  (* src = "fa.v:3.12-3.13" *)
  input b;
  wire b;
  (* src = "fa.v:3.15-3.18" *)
  input cin;
  wire cin;
  sky130_fd_sc_hd__maj3_1 _0_ (
    .A(a),
    .B(cin),
    .C(b),
    .X(cout)
  );
  sky130_fd_sc_hd__xor3_1 _1_ (
    .A(a),
    .B(cin),
    .C(b),
    .X(sum)
  );
endmodule
