/* Generated by Yosys 0.65 (git sha1 b85cad634, g++ 13.3.0-6ubuntu2~24.04.1 -fPIC -O3) */

(* top =  1  *)
(* src = "mux21.v:1.1-8.10" *)
module mux21(out, sel, a, b);
  (* src = "mux21.v:2.9-2.12" *)
  output out;
  wire out;
  (* src = "mux21.v:3.9-3.12" *)
  input sel;
  wire sel;
  (* src = "mux21.v:4.9-4.10" *)
  input a;
  wire a;
  (* src = "mux21.v:5.9-5.10" *)
  input b;
  wire b;
  sky130_fd_sc_hd__mux2_1 _0_ (
    .A0(a),
    .A1(b),
    .S(sel),
    .X(out)
  );
endmodule
